module VerifyExamples.Currency.IsValid0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Currency exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#isValid: \n\n    isValid (BankTime 101) {amount = Cents 123, currency = Complementary Cambiatus, issuedAt = BankTime 0, expiresAt = Infinite }\n    --> True" <|
        \() ->
            Expect.equal
                (
                isValid (BankTime 101) {amount = Cents 123, currency = Complementary Cambiatus, issuedAt = BankTime 0, expiresAt = Infinite }
                )
                (
                True
                )