module VerifyExamples.Currency.IsValid2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Currency exposing (..)







spec2 : Test.Test
spec2 =
    Test.test "#isValid: \n\n    isValid (BankTime 100) {amount = Cents 123, currency = Complementary Cambiatus, issuedAt = BankTime 0, expiresAt = Finite (BankTime 100) }\n    --> True" <|
        \() ->
            Expect.equal
                (
                isValid (BankTime 100) {amount = Cents 123, currency = Complementary Cambiatus, issuedAt = BankTime 0, expiresAt = Finite (BankTime 100) }
                )
                (
                True
                )