module VerifyExamples.Currency.StringFromCurrencyName0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Currency exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#stringFromCurrencyName: \n\n    stringFromCurrency (Complementary Cambiatus)\n    --> \"Cambiatus (C)\"" <|
        \() ->
            Expect.equal
                (
                stringFromCurrency (Complementary Cambiatus)
                )
                (
                "Cambiatus (C)"
                )