module VerifyExamples.Currency.StringFromMoney0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Currency exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#stringFromMoney: \n\n    stringFromMoney {amount = Cents 123, currency = Complementary Cambiatus, issuedAt = BankTime 0, expiresAt = Infinite }\n    --> \"1.23 Cambiatus (C) 0:Infinite\"" <|
        \() ->
            Expect.equal
                (
                stringFromMoney {amount = Cents 123, currency = Complementary Cambiatus, issuedAt = BankTime 0, expiresAt = Infinite }
                )
                (
                "1.23 Cambiatus (C) 0:Infinite"
                )