module VerifyExamples.Currency.StringFromCents0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Currency exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#stringFromCents: \n\n    stringFromCents (Cents 123)\n    --> \"1.23\"" <|
        \() ->
            Expect.equal
                (
                stringFromCents (Cents 123)
                )
                (
                "1.23"
                )