module VerifyExamples.Currency.Value2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Currency exposing (..)



acct2 : Account
acct2 = Account { currency = Complementary Cambiatus, transactions = [c1,c1]}
acct : Account
acct = Account { currency = Complementary Cambiatus, transactions = [c1]}
c1 : Money
c1 =  {amount = Cents 123, currency = Complementary Cambiatus, issuedAt = BankTime 0, expiresAt = Finite (BankTime 100) }



spec2 : Test.Test
spec2 =
    Test.test "#value: \n\n    value (BankTime 101) acct\n    --> Value (Complementary Cambiatus) (Cents 0)" <|
        \() ->
            Expect.equal
                (
                value (BankTime 101) acct
                )
                (
                Value (Complementary Cambiatus) (Cents 0)
                )