module VerifyExamples.Currency.ValueInCents0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Currency exposing (..)



acct2 : Account
acct2 = Account { currency = Complementary Cambiatus, transactions = [c1, c1]}
acct : Account
acct = Account { currency = Complementary Cambiatus, transactions = [c1]}
emptyAcct : Account
emptyAcct = Account { currency = Complementary Cambiatus, transactions = []}
c1 : Money
c1 =  {amount = Cents 123, currency = Complementary Cambiatus, issuedAt = BankTime 0, expiresAt = Finite (BankTime 100) }



spec0 : Test.Test
spec0 =
    Test.test "#valueInCents: \n\n    valueInCents acct2\n    --> (Cents 246)" <|
        \() ->
            Expect.equal
                (
                valueInCents acct2
                )
                (
                (Cents 246)
                )